# Travel Database for Python Streamlit version

travel_database = {
    'tokyo': {
        'id': 'tokyo',
        'name': 'Tokyo',
        'country': 'Japan',
        'coordinates': {'lat': 35.6762, 'lon': 139.6503},
        'description': 'A dazzling neon metropolis blending ultra-modern technology with historic temples and world-class dining.',
        'cover_image': 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?w=800&auto=format&fit=crop&q=80',
        'hotels': [
            {'id': 'tok_h1', 'name': 'Shinjuku Capsule Hostel', 'cost_level': 1, 'cost_approx': 35, 'rating': 4.2, 'coordinates': {'lat': 35.6905, 'lon': 139.7020}, 'description': 'Affordable, compact capsule sleeping in the heart of bustling Shinjuku.'},
            {'id': 'tok_h2', 'name': 'Hotel Gracery Shinjuku', 'cost_level': 2, 'cost_approx': 160, 'rating': 4.5, 'coordinates': {'lat': 35.6953, 'lon': 139.7022}, 'description': 'Famous Hotel with a giant Godzilla head on the terrace.'},
            {'id': 'tok_h3', 'name': 'Park Hyatt Tokyo', 'cost_level': 3, 'cost_approx': 650, 'rating': 4.9, 'coordinates': {'lat': 35.6856, 'lon': 139.6911}, 'description': 'Iconic luxury hotel offering majestic views of Mount Fuji.'}
        ],
        'dining': [
            {'id': 'tok_d1', 'name': 'Tsukiji Sushi Stall', 'meal_type': 'Breakfast', 'cost_level': 2, 'cost_approx': 20, 'dietary_flags': ['Gluten-Free'], 'coordinates': {'lat': 35.6655, 'lon': 139.7704}, 'description': 'Super fresh morning sashimi and sushi directly from vendors.'},
            {'id': 'tok_d2', 'name': 'Ichiran Ramen Shibuya', 'meal_type': 'Lunch', 'cost_level': 1, 'cost_approx': 12, 'dietary_flags': [], 'coordinates': {'lat': 35.6580, 'lon': 139.7016}, 'description': 'Famous individual booth style dining serving rich pork ramen.'},
            {'id': 'tok_d3', 'name': 'Vegan Gyoza Uzu', 'meal_type': 'Lunch', 'cost_level': 2, 'cost_approx': 18, 'dietary_flags': ['Vegan', 'Gluten-Free'], 'coordinates': {'lat': 35.6436, 'lon': 139.7900}, 'description': 'Spectacular digital art dining space serving gourmet vegan dumplings.'},
            {'id': 'tok_d4', 'name': 'Tempura Tsunahachi', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 35, 'dietary_flags': [], 'coordinates': {'lat': 35.6912, 'lon': 139.7030}, 'description': 'Classic tempura dining since 1924, frying vegetables and seafood.'},
            {'id': 'tok_d5', 'name': 'Halal Ramen Ouka', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 25, 'dietary_flags': ['Halal'], 'coordinates': {'lat': 35.6861, 'lon': 139.7109}, 'description': 'Highly rated halal-certified ramen served with rice and custom toppings.'},
            {'id': 'tok_d6', 'name': 'New York Grill', 'meal_type': 'Dinner', 'cost_level': 3, 'cost_approx': 150, 'dietary_flags': ['Gluten-Free'], 'coordinates': {'lat': 35.6856, 'lon': 139.6911}, 'description': 'Stunning 52nd-floor luxury dining featuring premium Wagyu steaks.'},
            {'id': 'tok_d7', 'name': 'FamilyMart Quick-Bites', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 5, 'dietary_flags': [], 'coordinates': {'lat': 35.6912, 'lon': 139.7030}, 'description': 'Famous Japanese convenience store snacks like Onigiri.'}
        ],
        'attractions': [
            {
                'id': 'tok_a1',
                'name': 'Sensō-ji Temple',
                'category': 'Culture',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 90,
                'coordinates': {'lat': 35.7147, 'lon': 139.7967},
                'description': 'Tokyos oldest and most iconic Buddhist temple, entered through the imposing Kaminarimon gate.',
                'image_url': 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=500&auto=format&fit=crop&q=80',
                'tips': 'Visit early in the morning or at night when the lanterns are lit.'
            },
            {
                'id': 'tok_a2',
                'name': 'Shinjuku Gyoen National Garden',
                'category': 'Nature',
                'cost_level': 1,
                'cost_approx': 4,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 35.6852, 'lon': 139.7101},
                'description': 'A massive park blending traditional Japanese, English, and French formal gardens.',
                'image_url': 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=500&auto=format&fit=crop&q=80',
                'tips': 'Perfect for cherry blossoms in spring. Alcohol is prohibited.'
            },
            {
                'id': 'tok_a3',
                'name': 'Shibuya Crossing & Shibuya Sky',
                'category': 'Shopping',
                'cost_level': 2,
                'cost_approx': 15,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 75,
                'coordinates': {'lat': 35.6580, 'lon': 139.7016},
                'description': 'The world\'s busiest pedestrian intersection, paired with an open-air rooftop observation deck.',
                'image_url': 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=500&auto=format&fit=crop&q=80',
                'tips': 'Book Shibuya Sky tickets online weeks in advance for sunset.'
            },
            {
                'id': 'tok_a4',
                'name': 'Mori Art Museum',
                'category': 'Culture',
                'cost_level': 2,
                'cost_approx': 16,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 100,
                'coordinates': {'lat': 35.6605, 'lon': 139.7292},
                'description': 'Contemporary museum located at the top of Mori Tower focusing on global modern art.',
                'image_url': 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=500&auto=format&fit=crop&q=80',
                'tips': 'Ticket includes access to the indoor Tokyo City View deck.'
            },
            {
                'id': 'tok_a5',
                'name': 'Tsukiji Outer Market Tour',
                'category': 'Food',
                'cost_level': 2,
                'cost_approx': 25,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 110,
                'coordinates': {'lat': 35.6655, 'lon': 139.7704},
                'description': 'A vibrant market packed with narrow alleys of fresh street food vendors.',
                'image_url': 'https://images.unsplash.com/photo-1558961309-dbdf660084dd?w=500&auto=format&fit=crop&q=80',
                'tips': 'Bring cash. Try the tamagoyaki and fresh oysters.'
            },
            {
                'id': 'tok_a6',
                'name': 'Akihabara Electric Town',
                'category': 'Shopping',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 35.6983, 'lon': 139.7715},
                'description': 'The epicenter of anime merchandise, retro video games, and electronics shops.',
                'image_url': 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&auto=format&fit=crop&q=80',
                'tips': 'Visit Radio Kaikan for multiple floors of collectibles.'
            },
            {
                'id': 'tok_a7',
                'name': 'Mt. Takao Hiking Trail',
                'category': 'Adventure',
                'cost_level': 1,
                'cost_approx': 8,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 240,
                'coordinates': {'lat': 35.6251, 'lon': 139.2437},
                'description': 'A beautiful forested mountain offering scenic hiking trails and a mountaintop shrine.',
                'image_url': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&auto=format&fit=crop&q=80',
                'tips': 'Take a cable car halfway up if you want to save energy.'
            },
            {
                'id': 'tok_a8',
                'name': 'teamLab Planets Digital Art',
                'category': 'Adventure',
                'cost_level': 3,
                'cost_approx': 28,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 120,
                'coordinates': {'lat': 35.6436, 'lon': 139.7900},
                'description': 'A museum where you walk through water and interact with digital light displays.',
                'image_url': 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&auto=format&fit=crop&q=80',
                'tips': 'You will walk barefoot through water up to knee-height.'
            },
            {
                'id': 'tok_a9',
                'name': 'Spa LaQua Onsen',
                'category': 'Relaxation',
                'cost_level': 3,
                'cost_approx': 30,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 180,
                'coordinates': {'lat': 35.7075, 'lon': 139.7533},
                'description': 'A massive hot-spring complex utilizing mineral-rich thermal water.',
                'image_url': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500&auto=format&fit=crop&q=80',
                'tips': 'Traditional rules apply (no swimwear in baths, and tattoos may be restricted).'
            },
            {
                'id': 'tok_a10',
                'name': 'Imperial Palace Gardens',
                'category': 'Historic',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 90,
                'coordinates': {'lat': 35.6869, 'lon': 139.7618},
                'description': 'The historic grounds of the former Edo Castle, with beautiful moats and gates.',
                'image_url': 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=500&auto=format&fit=crop&q=80',
                'tips': 'Closed on Mondays and Fridays.'
            }
        ]
    },
    'paris': {
        'id': 'paris',
        'name': 'Paris',
        'country': 'France',
        'coordinates': {'lat': 48.8566, 'lon': 2.3522},
        'description': 'The City of Light, famous for world-leading art galleries, majestic monuments, and romantic café culture.',
        'cover_image': 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
        'hotels': [
            {'id': 'par_h1', 'name': 'Generator Hostel Paris', 'cost_level': 1, 'cost_approx': 40, 'rating': 4.1, 'coordinates': {'lat': 48.8788, 'lon': 2.3705}, 'description': 'Stylishly designed hostel features a cool rooftop bar.'},
            {'id': 'par_h2', 'name': 'Hotel Les Deux Gares', 'cost_level': 2, 'cost_approx': 180, 'rating': 4.6, 'coordinates': {'lat': 48.8805, 'lon': 2.3575}, 'description': 'Charming hotel boasting colourful and eccentric retro French interiors.'},
            {'id': 'par_h3', 'name': 'The Ritz Paris', 'cost_level': 3, 'cost_approx': 950, 'rating': 4.9, 'coordinates': {'lat': 48.8681, 'lon': 2.3294}, 'description': 'One of the world\'s most legendary luxury hotels, overlooking Place Vendôme.'}
        ],
        'dining': [
            {'id': 'par_d1', 'name': 'Boulangerie Utopie', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 6, 'dietary_flags': [], 'coordinates': {'lat': 48.8617, 'lon': 2.3685}, 'description': 'Artisanal croissants, sourdough, and modern black-crust baguettes.'},
            {'id': 'par_d2', 'name': 'L\'As du Fallafel', 'meal_type': 'Lunch', 'cost_level': 1, 'cost_approx': 10, 'dietary_flags': ['Vegan', 'Halal'], 'coordinates': {'lat': 48.8576, 'lon': 2.3590}, 'description': 'Renowned counter-serve spot in the Jewish Quarter serving falafel.'},
            {'id': 'par_d3', 'name': 'Café de Flore', 'meal_type': 'Breakfast', 'cost_level': 2, 'cost_approx': 22, 'dietary_flags': [], 'coordinates': {'lat': 48.8542, 'lon': 2.3287}, 'description': 'Famous historic cafe in St. Germain, once the meeting spot of philosophers.'},
            {'id': 'par_d4', 'name': 'Relais de l\'Entrecôte', 'meal_type': 'Lunch', 'cost_level': 2, 'cost_approx': 30, 'dietary_flags': [], 'coordinates': {'lat': 48.8502, 'lon': 2.3275}, 'description': 'Bustling bistro famous for steak frites served with secret herb sauce.'},
            {'id': 'par_d5', 'name': 'Potager du Marais', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 35, 'dietary_flags': ['Vegan', 'Gluten-Free'], 'coordinates': {'lat': 48.8590, 'lon': 2.3600}, 'description': 'Cosy restaurant cooking traditional French cuisine in vegan form.'},
            {'id': 'par_d6', 'name': 'Le Jules Verne', 'meal_type': 'Dinner', 'cost_level': 3, 'cost_approx': 220, 'dietary_flags': ['Gluten-Free'], 'coordinates': {'lat': 48.8584, 'lon': 2.2945}, 'description': 'Michelin-starred restaurant situated inside the Eiffel Tower.'},
            {'id': 'par_d7', 'name': 'L\'Alchimiste Café', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 8, 'dietary_flags': ['Vegan'], 'coordinates': {'lat': 48.8590, 'lon': 2.3700}, 'description': 'Modern specialty coffee roastery with plant-based selections.'}
        ],
        'attractions': [
            {
                'id': 'par_a1',
                'name': 'Eiffel Tower Tour',
                'category': 'Historic',
                'cost_level': 2,
                'cost_approx': 26,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 48.8584, 'lon': 2.2945},
                'description': 'The monumental iron lattice tower on the Champ de Mars, symbol of Paris.',
                'image_url': 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500&auto=format&fit=crop&q=80',
                'tips': 'Book summit elevator tickets online months in advance.'
            },
            {
                'id': 'par_a2',
                'name': 'Louvre Museum',
                'category': 'Culture',
                'cost_level': 2,
                'cost_approx': 20,
                'intensity': 'High',
                'is_indoor': True,
                'duration': 180,
                'coordinates': {'lat': 48.8606, 'lon': 2.3376},
                'description': 'The world\'s largest art museum, home to the Mona Lisa.',
                'image_url': 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=500&auto=format&fit=crop&q=80',
                'tips': 'Enter through the Carrousel du Louvre shopping mall to bypass main lines.'
            },
            {
                'id': 'par_a3',
                'name': 'Seine River Cruise',
                'category': 'Relaxation',
                'cost_level': 2,
                'cost_approx': 18,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 60,
                'coordinates': {'lat': 48.8625, 'lon': 2.3255},
                'description': 'A relaxing glass-canopied boat cruise along the Seine.',
                'image_url': 'https://images.unsplash.com/photo-1503917988258-f87a78e3c995?w=500&auto=format&fit=crop&q=80',
                'tips': 'Board the cruise at sunset to watch the monuments light up.'
            },
            {
                'id': 'par_a4',
                'name': 'Palace of Versailles',
                'category': 'Historic',
                'cost_level': 3,
                'cost_approx': 30,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 240,
                'coordinates': {'lat': 48.8048, 'lon': 2.1204},
                'description': 'The opulent principal royal residence of France from 1682.',
                'image_url': 'https://images.unsplash.com/photo-1585672841967-df507df05e26?w=500&auto=format&fit=crop&q=80',
                'tips': 'Take RER C train from central Paris. Don\'t miss the Hall of Mirrors.'
            },
            {
                'id': 'par_a5',
                'name': 'Musée d\'Orsay',
                'category': 'Culture',
                'cost_level': 2,
                'cost_approx': 16,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 120,
                'coordinates': {'lat': 48.8599, 'lon': 2.3265},
                'description': 'Museum located in a magnificent former railway station housing Impressionist art.',
                'image_url': 'https://images.unsplash.com/photo-1601887389937-0b02c26b6c3c?w=500&auto=format&fit=crop&q=80',
                'tips': 'Head to the top floor first to see iconic paintings by Monet and Van Gogh.'
            },
            {
                'id': 'par_a6',
                'name': 'Montmartre & Sacré-Cœur Walk',
                'category': 'Culture',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 100,
                'coordinates': {'lat': 48.8867, 'lon': 2.3431},
                'description': 'An artistic hilltop district with winding cobblestone streets.',
                'image_url': 'https://images.unsplash.com/photo-1509840144521-88894172c72b?w=500&auto=format&fit=crop&q=80',
                'tips': 'Use the funicular train if the steep stairs are too tiring.'
            },
            {
                'id': 'par_a7',
                'name': 'Luxembourg Gardens Park',
                'category': 'Nature',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 90,
                'coordinates': {'lat': 48.8462, 'lon': 2.3372},
                'description': 'A 25-hectare tranquil oasis of lawns and model sailboat ponds.',
                'image_url': 'https://images.unsplash.com/photo-1549887534-1541e9326642?w=500&auto=format&fit=crop&q=80',
                'tips': 'Grab one of the famous sage-green metal chairs and relax.'
            },
            {
                'id': 'par_a8',
                'name': 'Catacombs of Paris',
                'category': 'Adventure',
                'cost_level': 2,
                'cost_approx': 29,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 90,
                'coordinates': {'lat': 48.8338, 'lon': 2.3324},
                'description': 'Underground ossuaries holding the skeletal remains of over six million people.',
                'image_url': 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=500&auto=format&fit=crop&q=80',
                'tips': 'Temperatures remain cool (14°C) year-round. Not for the claustrophobic.'
            },
            {
                'id': 'par_a9',
                'name': 'Marne River Kayaking',
                'category': 'Adventure',
                'cost_level': 3,
                'cost_approx': 45,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 150,
                'coordinates': {'lat': 48.8250, 'lon': 2.4800},
                'description': 'An active, scenic kayaking trip through the Marne loops.',
                'image_url': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=500&auto=format&fit=crop&q=80',
                'tips': 'Easily accessible via RER A train. Wet-bags are provided.'
            },
            {
                'id': 'par_a10',
                'name': 'Galeries Lafayette Shopping',
                'category': 'Shopping',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 90,
                'coordinates': {'lat': 48.8732, 'lon': 2.3323},
                'description': 'High-end department store famous for its stunning stained-glass dome.',
                'image_url': 'https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=500&auto=format&fit=crop&q=80',
                'tips': 'The rooftop terrace is completely free and offers panoramic views.'
            }
        ]
    },
    'rome': {
        'id': 'rome',
        'name': 'Rome',
        'country': 'Italy',
        'coordinates': {'lat': 41.8960, 'lon': 12.4820},
        'description': 'An open-air museum filled with classical ruins, vibrant piazzas, and delicious pasta.',
        'cover_image': 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80',
        'hotels': [
            {'id': 'rom_h1', 'name': 'The Beehive Cozy Hostel', 'cost_level': 1, 'cost_approx': 38, 'rating': 4.3, 'coordinates': {'lat': 41.9022, 'lon': 12.5042}, 'description': 'Relaxed, organic cafe and hostel gardens near Termini.'},
            {'id': 'rom_h2', 'name': 'Hotel Santa Maria', 'cost_level': 2, 'cost_approx': 175, 'rating': 4.7, 'coordinates': {'lat': 41.8895, 'lon': 12.4695}, 'description': 'Converted historic convent in Trastevere around a courtyard.'},
            {'id': 'rom_h3', 'name': 'J.K. Place Roma', 'cost_level': 3, 'cost_approx': 680, 'rating': 4.9, 'coordinates': {'lat': 41.9029, 'lon': 12.4770}, 'description': 'Ultra-chic boutique hotel featuring elegant style.'}
        ],
        'dining': [
            {'id': 'rom_d1', 'name': 'Roscioli Caffè', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 8, 'dietary_flags': [], 'coordinates': {'lat': 41.8942, 'lon': 12.4725}, 'description': 'Legendary espresso and Maritozzo.'},
            {'id': 'rom_d2', 'name': 'Pizzarium Bonci', 'meal_type': 'Lunch', 'cost_level': 1, 'cost_approx': 12, 'dietary_flags': ['Vegan'], 'coordinates': {'lat': 41.9077, 'lon': 12.4470}, 'description': 'Acclaimed gourmet Roman pizza-by-the-slice.'},
            {'id': 'rom_d3', 'name': 'Buddy Veggy Restaurant', 'meal_type': 'Lunch', 'cost_level': 2, 'cost_approx': 20, 'dietary_flags': ['Vegan', 'Gluten-Free'], 'coordinates': {'lat': 41.8973, 'lon': 12.4780}, 'description': 'Plant-based twists on carbonara and classic Italian dishes.'},
            {'id': 'rom_d4', 'name': 'Da Enzo al 29', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 28, 'dietary_flags': [], 'coordinates': {'lat': 41.8884, 'lon': 12.4782}, 'description': 'Tiny, popular Trastevere trattoria serving Roman classics.'},
            {'id': 'rom_d5', 'name': 'Rifugio Romano', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 32, 'dietary_flags': ['Vegan', 'Gluten-Free'], 'coordinates': {'lat': 41.9038, 'lon': 12.5020}, 'description': 'Cosy family-run eatery serving fully veganized Roman dishes.'},
            {'id': 'rom_d6', 'name': 'La Pergola', 'meal_type': 'Dinner', 'cost_level': 3, 'cost_approx': 290, 'dietary_flags': ['Gluten-Free', 'Halal'], 'coordinates': {'lat': 41.9192, 'lon': 12.4460}, 'description': 'Romes only 3-Michelin-star restaurant.'},
            {'id': 'rom_d7', 'name': 'Giolitti Gelato', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 5, 'dietary_flags': ['Gluten-Free'], 'coordinates': {'lat': 41.9009, 'lon': 12.4776}, 'description': 'Romes oldest and most famous gelateria.'}
        ],
        'attractions': [
            {
                'id': 'rom_a1',
                'name': 'Colosseum & Forum',
                'category': 'Historic',
                'cost_level': 2,
                'cost_approx': 22,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 150,
                'coordinates': {'lat': 41.8902, 'lon': 12.4922},
                'description': 'The monumental stone amphitheater of antiquity.',
                'image_url': 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=500&auto=format&fit=crop&q=80',
                'tips': 'Book Arena or Underground tour path in advance.'
            },
            {
                'id': 'rom_a2',
                'name': 'Vatican Museums',
                'category': 'Culture',
                'cost_level': 2,
                'cost_approx': 25,
                'intensity': 'High',
                'is_indoor': True,
                'duration': 180,
                'coordinates': {'lat': 41.9060, 'lon': 12.4536},
                'description': 'Vast collection of classical sculptures and the Sistine Chapel.',
                'image_url': 'https://images.unsplash.com/photo-1542820229-081e0c12af0b?w=500&auto=format&fit=crop&q=80',
                'tips': 'Strict dress code required: shoulders and knees covered.'
            },
            {
                'id': 'rom_a3',
                'name': 'Trevi Fountain & Steps',
                'category': 'Historic',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 75,
                'coordinates': {'lat': 41.9009, 'lon': 12.4833},
                'description': 'The colossal baroque fountain of Neptune, paired with Spanish Steps.',
                'image_url': 'https://images.unsplash.com/photo-1529154036614-a3ad9727ab78?w=500&auto=format&fit=crop&q=80',
                'tips': 'Throw a coin over your left shoulder to guarantee return.'
            },
            {
                'id': 'rom_a4',
                'name': 'Borghese Gallery & Villa Gardens',
                'category': 'Nature',
                'cost_level': 2,
                'cost_approx': 18,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 41.9142, 'lon': 12.4921},
                'description': 'A grand English-style landscaped park hosting a museum.',
                'image_url': 'https://images.unsplash.com/photo-1549887534-1541e9326642?w=500&auto=format&fit=crop&q=80',
                'tips': 'Renting a golf cart is a fun way to explore the gardens.'
            },
            {
                'id': 'rom_a5',
                'name': 'Pantheon',
                'category': 'Historic',
                'cost_level': 1,
                'cost_approx': 5,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 45,
                'coordinates': {'lat': 41.8986, 'lon': 12.4769},
                'description': 'A former Roman temple, now a church, featuring a concrete dome.',
                'image_url': 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=500&auto=format&fit=crop&q=80',
                'tips': 'Look up at the oculus. On rainy days, water drains through floor holes.'
            },
            {
                'id': 'rom_a6',
                'name': 'Trastevere Walking Tour',
                'category': 'Food',
                'cost_level': 2,
                'cost_approx': 20,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 41.8885, 'lon': 12.4690},
                'description': 'An atmospheric neighborhood characterized by bohemian charm.',
                'image_url': 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?w=500&auto=format&fit=crop&q=80',
                'tips': 'Visit after dark when the squares come alive.'
            },
            {
                'id': 'rom_a7',
                'name': 'Catacombs of St. Callixtus',
                'category': 'Adventure',
                'cost_level': 2,
                'cost_approx': 10,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 90,
                'coordinates': {'lat': 41.8594, 'lon': 12.5112},
                'description': 'The ancient underground cemetery tunnels of early Christians.',
                'image_url': 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=500&auto=format&fit=crop&q=80',
                'tips': 'Located along Appian Way. Rent a bicycle.'
            },
            {
                'id': 'rom_a8',
                'name': 'Pasta & Tiramisu Masterclass',
                'category': 'Food',
                'cost_level': 3,
                'cost_approx': 55,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 150,
                'coordinates': {'lat': 41.8990, 'lon': 12.4760},
                'description': 'An interactive cooking class preparing fettuccine and tiramisu.',
                'image_url': 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&auto=format&fit=crop&q=80',
                'tips': 'Come hungry! Includes multiple courses and local wine.'
            },
            {
                'id': 'rom_a9',
                'name': 'Ostia Antica Ruins',
                'category': 'Adventure',
                'cost_level': 2,
                'cost_approx': 14,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 210,
                'coordinates': {'lat': 41.7610, 'lon': 12.2858},
                'description': 'A massive archaeological site that was the harbor city of Rome.',
                'image_url': 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=500&auto=format&fit=crop&q=80',
                'tips': 'Take the Roma-Lido suburban train (25 minutes).'
            },
            {
                'id': 'rom_a10',
                'name': 'QC Termeroma Spa',
                'category': 'Relaxation',
                'cost_level': 3,
                'cost_approx': 60,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 180,
                'coordinates': {'lat': 41.8000, 'lon': 12.4000},
                'description': 'A historic-style spa offering therapeutic baths and saunas.',
                'image_url': 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500&auto=format&fit=crop&q=80',
                'tips': 'Reservations are required.'
            }
        ]
    },
    'newyork': {
        'id': 'newyork',
        'name': 'New York',
        'country': 'USA',
        'coordinates': {'lat': 40.7128, 'lon': -74.0060},
        'description': 'The city that never sleeps, packed with iconic skyscrapers and green urban high-lines.',
        'cover_image': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=80',
        'hotels': [
            {'id': 'nyc_h1', 'name': 'Freehand New York', 'cost_level': 1, 'cost_approx': 120, 'rating': 4.2, 'coordinates': {'lat': 40.7397, 'lon': -73.9840}, 'description': 'Trendy, artistic hostel/hotel in Flatiron.'},
            {'id': 'nyc_h2', 'name': 'The Ludlow Hotel', 'cost_level': 2, 'cost_approx': 290, 'rating': 4.6, 'coordinates': {'lat': 40.7218, 'lon': -73.9872}, 'description': 'Loft-style boutique hotel in the Lower East Side.'},
            {'id': 'nyc_h3', 'name': 'The Plaza Hotel', 'cost_level': 3, 'cost_approx': 850, 'rating': 4.8, 'coordinates': {'lat': 40.7645, 'lon': -73.9744}, 'description': 'Historic landmark luxury hotel overlooking Central Park.'}
        ],
        'dining': [
            {'id': 'nyc_d1', 'name': 'Ess-a-Bagel', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 12, 'dietary_flags': ['Vegan'], 'coordinates': {'lat': 40.7570, 'lon': -73.9690}, 'description': 'Famous hand-rolled bagels with tofu cream cheese.'},
            {'id': 'nyc_d2', 'name': 'Katz\'s Delicatessen', 'meal_type': 'Lunch', 'cost_level': 2, 'cost_approx': 28, 'dietary_flags': ['Halal'], 'coordinates': {'lat': 40.7222, 'lon': -73.9874}, 'description': 'Legendary Jewish deli serving pastrami sandwiches.'},
            {'id': 'nyc_d3', 'name': 'Beatnic (Vegan Burger)', 'meal_type': 'Lunch', 'cost_level': 1, 'cost_approx': 15, 'dietary_flags': ['Vegan', 'Gluten-Free'], 'coordinates': {'lat': 40.7300, 'lon': -74.0000}, 'description': 'Casual spot cooking plant-based burgers.'},
            {'id': 'nyc_d4', 'name': 'Carbone', 'meal_type': 'Dinner', 'cost_level': 3, 'cost_approx': 130, 'dietary_flags': [], 'coordinates': {'lat': 40.7279, 'lon': -74.0002}, 'description': 'High-end, retro-themed Italian-American joint.'},
            {'id': 'nyc_d5', 'name': 'Nomad Vegetarian Diner', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 35, 'dietary_flags': ['Vegan', 'Gluten-Free'], 'coordinates': {'lat': 40.7450, 'lon': -73.9880}, 'description': 'Art-deco styled diner cooking gluten-free vegan dishes.'},
            {'id': 'nyc_d6', 'name': 'Clinton St. Baking Co.', 'meal_type': 'Breakfast', 'cost_level': 2, 'cost_approx': 24, 'dietary_flags': [], 'coordinates': {'lat': 40.7212, 'lon': -73.9840}, 'description': 'Acclaimed diner famous for pancakes.'}
        ],
        'attractions': [
            {
                'id': 'nyc_a1',
                'name': 'Statue of Liberty & Ellis Island',
                'category': 'Historic',
                'cost_level': 2,
                'cost_approx': 24,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 180,
                'coordinates': {'lat': 40.6892, 'lon': -74.0445},
                'description': 'America\'s monumental copper beacon of liberty.',
                'image_url': 'https://images.unsplash.com/photo-1508849789987-4e5333c12b78?w=500&auto=format&fit=crop&q=80',
                'tips': 'Take the earliest morning ferry to avoid security lines.'
            },
            {
                'id': 'nyc_a2',
                'name': 'Metropolitan Museum of Art',
                'category': 'Culture',
                'cost_level': 2,
                'cost_approx': 25,
                'intensity': 'High',
                'is_indoor': True,
                'duration': 180,
                'coordinates': {'lat': 40.7794, 'lon': -73.9632},
                'description': 'One of the world\'s largest art museums, spanning 5,000 years.',
                'image_url': 'https://images.unsplash.com/photo-1601887389937-0b02c26b6c3c?w=500&auto=format&fit=crop&q=80',
                'tips': 'Visit the rooftop garden during summer for park views.'
            },
            {
                'id': 'nyc_a3',
                'name': 'Central Park Bicycle Loop',
                'category': 'Nature',
                'cost_level': 2,
                'cost_approx': 15,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 40.7850, 'lon': -73.9683},
                'description': 'An active cycle ride through the scenic lanes of Central Park.',
                'image_url': 'https://images.unsplash.com/photo-1513826308400-30c72d579499?w=500&auto=format&fit=crop&q=80',
                'tips': 'Bikes are restricted to the main circular drive.'
            },
            {
                'id': 'nyc_a4',
                'name': 'Empire State Building',
                'category': 'Historic',
                'cost_level': 3,
                'cost_approx': 44,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 90,
                'coordinates': {'lat': 40.7484, 'lon': -73.9857},
                'description': 'The world-famous Art Deco skyscraper.',
                'image_url': 'https://images.unsplash.com/photo-1522083165195-342750297f05?w=500&auto=format&fit=crop&q=80',
                'tips': 'Reserve late hours to see the city lights without crowds.'
            },
            {
                'id': 'nyc_a5',
                'name': 'Broadway Theatre Show',
                'category': 'Culture',
                'cost_level': 3,
                'cost_approx': 95,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 150,
                'coordinates': {'lat': 40.7590, 'lon': -73.9845},
                'description': 'World-renowned live theatrical performances.',
                'image_url': 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=500&auto=format&fit=crop&q=80',
                'tips': 'Visit the TKTS booth for up to 50% off tickets.'
            },
            {
                'id': 'nyc_a6',
                'name': 'High Line & Chelsea Market',
                'category': 'Relaxation',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 110,
                'coordinates': {'lat': 40.7480, 'lon': -74.0048},
                'description': 'An elevated linear park built on a historic rail line.',
                'image_url': 'https://images.unsplash.com/photo-1507038772120-7bef2c384c5e?w=500&auto=format&fit=crop&q=80',
                'tips': 'Walk south to Chelsea Market, where you can grab lunch.'
            },
            {
                'id': 'nyc_a7',
                'name': 'Summit One Vanderbilt',
                'category': 'Adventure',
                'cost_level': 3,
                'cost_approx': 42,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 90,
                'coordinates': {'lat': 40.7528, 'lon': -73.9789},
                'description': 'An immersive multi-sensory observation deck.',
                'image_url': 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&auto=format&fit=crop&q=80',
                'tips': 'Sunglasses are highly recommended due to high reflections.'
            },
            {
                'id': 'nyc_a8',
                'name': 'Manhattan Helicopter Charter',
                'category': 'Adventure',
                'cost_level': 3,
                'cost_approx': 210,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 45,
                'coordinates': {'lat': 40.7015, 'lon': -74.0090},
                'description': 'A thrilling aerial helicopter flight over Manhattan.',
                'image_url': 'https://images.unsplash.com/photo-1522083165195-342750297f05?w=500&auto=format&fit=crop&q=80',
                'tips': 'Booking in the afternoon offers the best lighting.'
            },
            {
                'id': 'nyc_a9',
                'name': 'Brooklyn Bridge Crossing',
                'category': 'Historic',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 75,
                'coordinates': {'lat': 40.7061, 'lon': -73.9969},
                'description': 'The historic suspension bridge spanning the East River.',
                'image_url': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=500&auto=format&fit=crop&q=80',
                'tips': 'Walk from the Brooklyn side to see the skyline in front of you.'
            },
            {
                'id': 'nyc_a10',
                'name': 'SoHo Gallery Walk',
                'category': 'Shopping',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 100,
                'coordinates': {'lat': 40.7233, 'lon': -74.0017},
                'description': 'Strolling through cast-iron architecture streets and galleries.',
                'image_url': 'https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=500&auto=format&fit=crop&q=80',
                'tips': 'Stop by local bakeries on Lafayette St for pastries.'
            }
        ]
    },
    'cairo': {
        'id': 'cairo',
        'name': 'Cairo',
        'country': 'Egypt',
        'coordinates': {'lat': 30.0444, 'lon': 31.2357},
        'description': 'The cradle of civilization, hosting colossal ancient monuments and the grand Nile river.',
        'cover_image': 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&auto=format&fit=crop&q=80',
        'hotels': [
            {'id': 'cai_h1', 'name': 'Dahab Downtown Hostel', 'cost_level': 1, 'cost_approx': 18, 'rating': 4.4, 'coordinates': {'lat': 30.0490, 'lon': 31.2395}, 'description': 'A cozy backpacker haven on a downtown rooftop garden.'},
            {'id': 'cai_h2', 'name': 'Steigenberger Hotel Tahrir', 'cost_level': 2, 'cost_approx': 110, 'rating': 4.6, 'coordinates': {'lat': 30.0475, 'lon': 31.2345}, 'description': 'Sleek, modern business hotel steps away from Tahrir Square.'},
            {'id': 'cai_h3', 'name': 'Four Seasons Nile Plaza', 'cost_level': 3, 'cost_approx': 450, 'rating': 4.9, 'coordinates': {'lat': 30.0350, 'lon': 31.2290}, 'description': 'High-end luxury resort boasting views of the Nile.'}
        ],
        'dining': [
            {'id': 'cai_d1', 'name': 'El Felfela Café', 'meal_type': 'Breakfast', 'cost_level': 1, 'cost_approx': 6, 'dietary_flags': ['Vegan', 'Halal'], 'coordinates': {'lat': 30.0485, 'lon': 31.2390}, 'description': 'Traditional Egyptian breakfast of ful mudammas and falafel.'},
            {'id': 'cai_d2', 'name': 'Abou Tarek Koshary', 'meal_type': 'Lunch', 'cost_level': 1, 'cost_approx': 5, 'dietary_flags': ['Vegan', 'Halal'], 'coordinates': {'lat': 30.0522, 'lon': 31.2394}, 'description': 'Cairo\'s most famous restaurant dedicated to the national dish Koshary.'},
            {'id': 'cai_d3', 'name': 'Zooba Restaurant', 'meal_type': 'Lunch', 'cost_level': 2, 'cost_approx': 12, 'dietary_flags': ['Vegan', 'Halal', 'Gluten-Free'], 'coordinates': {'lat': 30.0610, 'lon': 31.2210}, 'description': 'Gourmet organic twists on Egyptian street food classics.'},
            {'id': 'cai_d4', 'name': 'Abou El Sid', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 24, 'dietary_flags': ['Halal'], 'coordinates': {'lat': 30.0630, 'lon': 31.2190}, 'description': 'Authentic recipes in an intricately decorated setting.'},
            {'id': 'cai_d5', 'name': 'Andrea El Mariouteya', 'meal_type': 'Dinner', 'cost_level': 2, 'cost_approx': 20, 'dietary_flags': ['Halal'], 'coordinates': {'lat': 29.9820, 'lon': 31.1410}, 'description': 'Famous garden dining serving spiced rotisserie chicken.'},
            {'id': 'cai_d6', 'name': 'The Revolving Restaurant', 'meal_type': 'Dinner', 'cost_level': 3, 'cost_approx': 90, 'dietary_flags': ['Halal', 'Gluten-Free'], 'coordinates': {'lat': 30.0320, 'lon': 31.2260}, 'description': 'Rotating dining room atop the Grand Nile Tower.'}
        ],
        'attractions': [
            {
                'id': 'cai_a1',
                'name': 'Giza Pyramids & Sphinx',
                'category': 'Historic',
                'cost_level': 2,
                'cost_approx': 15,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 180,
                'coordinates': {'lat': 29.9792, 'lon': 31.1342},
                'description': 'The monumental ancient tombs of Giza and the Sphinx.',
                'image_url': 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=500&auto=format&fit=crop&q=80',
                'tips': 'Agree on a camel ride price before mounting.'
            },
            {
                'id': 'cai_a2',
                'name': 'Grand Egyptian Museum',
                'category': 'Culture',
                'cost_level': 2,
                'cost_approx': 20,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 180,
                'coordinates': {'lat': 29.9920, 'lon': 31.1210},
                'description': 'The colossal museum housing the collection of pharaonic antiquities.',
                'image_url': 'https://images.unsplash.com/photo-1503177119275-0aa32b31d468?w=500&auto=format&fit=crop&q=80',
                'tips': 'Book guided tours of the grand atrium online.'
            },
            {
                'id': 'cai_a3',
                'name': 'Khan el-Khalili Bazaar Walk',
                'category': 'Culture',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 30.0478, 'lon': 31.2625},
                'description': 'A labyrinth of narrow historic souk alleyways smelling of spices.',
                'image_url': 'https://images.unsplash.com/photo-1568322422390-eeec11075678?w=500&auto=format&fit=crop&q=80',
                'tips': 'Bargaining is expected. Offer 45% of initial price and work up.'
            },
            {
                'id': 'cai_a4',
                'name': ' Citadel & Alabaster Mosque',
                'category': 'Historic',
                'cost_level': 1,
                'cost_approx': 6,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 90,
                'coordinates': {'lat': 30.0299, 'lon': 31.2622},
                'description': 'The medieval fortification of Salah ad-Din, topped by Alabaster mosque.',
                'image_url': 'https://images.unsplash.com/photo-1569429593410-b498b3fb3387?w=500&auto=format&fit=crop&q=80',
                'tips': 'Go at sunset to view the entire city.'
            },
            {
                'id': 'cai_a5',
                'name': 'Nile River Felucca Ride',
                'category': 'Relaxation',
                'cost_level': 1,
                'cost_approx': 10,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 75,
                'coordinates': {'lat': 30.0410, 'lon': 31.2280},
                'description': 'A peaceful sail on a traditional wooden boat along the Nile.',
                'image_url': 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=500&auto=format&fit=crop&q=80',
                'tips': 'Rent the entire boat rather than individual tickets.'
            },
            {
                'id': 'cai_a6',
                'name': 'Al-Azhar Park Oasis',
                'category': 'Nature',
                'cost_level': 1,
                'cost_approx': 2,
                'intensity': 'Low',
                'is_indoor': False,
                'duration': 90,
                'coordinates': {'lat': 30.0410, 'lon': 31.2650},
                'description': 'A 30-hectare lush green sanctuary offering manicured gardens.',
                'image_url': 'https://images.unsplash.com/photo-1549887534-1541e9326642?w=500&auto=format&fit=crop&q=80',
                'tips': 'Great spots for lunch inside with panoramic views.'
            },
            {
                'id': 'cai_a7',
                'name': 'Desert Quad Biking at Pyramids',
                'category': 'Adventure',
                'cost_level': 2,
                'cost_approx': 30,
                'intensity': 'High',
                'is_indoor': False,
                'duration': 120,
                'coordinates': {'lat': 29.9650, 'lon': 31.1000},
                'description': 'Riding quad bikes across the desert dunes flanking the Pyramids.',
                'image_url': 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&auto=format&fit=crop&q=80',
                'tips': 'Wear sunglasses and a scarf to protect against sand.'
            },
            {
                'id': 'cai_a8',
                'name': 'Coptic Cairo Churches Tour',
                'category': 'Historic',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': False,
                'duration': 100,
                'coordinates': {'lat': 30.0060, 'lon': 31.2300},
                'description': 'The historic old sector featuring the Hanging Church.',
                'image_url': 'https://images.unsplash.com/photo-1529154036614-a3ad9727ab78?w=500&auto=format&fit=crop&q=80',
                'tips': 'Quiet and peaceful. Reached easily by metro to Mar Girgis.'
            },
            {
                'id': 'cai_a9',
                'name': 'Cave Church of St. Simon',
                'category': 'Adventure',
                'cost_level': 1,
                'cost_approx': 0,
                'intensity': 'Medium',
                'is_indoor': True,
                'duration': 90,
                'coordinates': {'lat': 30.0310, 'lon': 31.2720},
                'description': 'A massive church carved directly into the Mokattam Mountain.',
                'image_url': 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=500&auto=format&fit=crop&q=80',
                'tips': 'Requires driving through Garbage City. Use a reliable driver.'
            },
            {
                'id': 'cai_a10',
                'name': 'Egyptian Cooking Class',
                'category': 'Food',
                'cost_level': 2,
                'cost_approx': 35,
                'intensity': 'Low',
                'is_indoor': True,
                'duration': 120,
                'coordinates': {'lat': 30.0450, 'lon': 31.2350},
                'description': 'Learn to prepare classic Egyptian street dishes like Hawawshi.',
                'image_url': 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&auto=format&fit=crop&q=80',
                'tips': 'Includes walking through local markets to buy ingredients.'
            }
        ]
    }
}

simulator_events = [
    {
        'id': 'ev_weather_rain',
        'type': 'WEATHER',
        'title': 'Sudden Rain Shower',
        'description': 'Heavy precipitation sweeps across the city, making outdoor sights muddy and uncomfortable.',
        'trigger_condition': 'Weather changes to rainy',
        'impact_description': 'Swaps outdoor sights with indoor ones and replaces walking with transit/cabs.'
    },
    {
        'id': 'ev_traffic_delay',
        'type': 'TRAFFIC',
        'title': 'Major Traffic Gridlock',
        'description': 'A vehicle breakdown on the main road increases transit times by 40 minutes.',
        'trigger_condition': 'Traffic level rises to high',
        'impact_description': 'Shrinks activity durations and delays dinner/sights.'
    },
    {
        'id': 'ev_crowd_spike',
        'type': 'CROWD',
        'title': 'Extreme Attraction Crowd Spike',
        'description': 'Large tour groups trigger ticket queue wait times to exceed 2+ hours.',
        'trigger_condition': 'Crowd alert occurs',
        'impact_description': 'Reschedules crowded attraction to a quiet park or relaxation day.'
    },
    {
        'id': 'ev_budget_alert',
        'type': 'BUDGET',
        'title': 'Budget Threshold Exceeded',
        'description': 'Calculated spending exceeds your target limits by 15%.',
        'trigger_condition': 'Expenses > Budget limit',
        'impact_description': 'Swaps premium meals with street food and expensive attractions with free ones.'
    }
]
